package main

import (
	"fmt"
	"os"
	"strings"
	"text/tabwriter"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/doze-dev/doze/internal/modules"
	"github.com/doze-dev/doze/internal/ui"
)

// moduleMeta mirrors the registry's meta.yaml (generated by `dzm meta` from the
// driver's Describe(), so it can't drift from what the module actually decodes).
type moduleMeta struct {
	Title        string     `yaml:"title"`
	Tagline      string     `yaml:"tagline"`
	Category     string     `yaml:"category"`
	Engine       string     `yaml:"engine"`
	Port         int        `yaml:"port"`
	Example      string     `yaml:"example"`
	ExampleLabel string     `yaml:"exampleLabel"`
	Description  string     `yaml:"description"`
	Homepage     string     `yaml:"homepage"`
	Config       metaConfig `yaml:"config"`
}

type metaConfig struct {
	Arguments []metaArg   `yaml:"arguments"`
	Blocks    []metaBlock `yaml:"blocks"`
}

type metaBlock struct {
	Name      string    `yaml:"name"`
	Label     string    `yaml:"label"`
	Desc      string    `yaml:"desc"`
	Arguments []metaArg `yaml:"arguments"`
}

type metaArg struct {
	Name     string `yaml:"name"`
	Type     string `yaml:"type"`
	Default  string `yaml:"default"`
	Desc     string `yaml:"desc"`
	Required bool   `yaml:"required"`
	Since    string `yaml:"since"`
	Until    string `yaml:"until"`
}

func modulesDocsCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "docs <engine-type|source>",
		Short: "Show a module's configuration reference in the terminal",
		Long: "docs fetches a module's generated documentation from the registry — every\n" +
			"argument and nested block its config accepts, with defaults and the engine\n" +
			"versions that gate them — so you can write the block without leaving the\n" +
			"terminal. The same data renders at the registry site.",
		Args: cobra.ExactArgs(1),
		RunE: func(_ *cobra.Command, args []string) error {
			source := args[0]
			if !strings.Contains(source, "/") {
				source = modules.DefaultNamespace + "/" + source
			}
			mm, err := modules.NewManager(dozeHome())
			if err != nil {
				return err
			}
			meta, err := mm.Meta(source)
			if err != nil {
				return err
			}
			renderModuleDocs(source, meta)
			return nil
		},
	}
}

func renderModuleDocs(source string, raw []byte) {
	var m moduleMeta
	if err := yaml.Unmarshal(raw, &m); err != nil || m.Title == "" {
		// Serve whatever the registry has rather than nothing.
		fmt.Print(string(raw))
		return
	}

	fmt.Printf("%s — %s\n", ui.Title(m.Title), m.Tagline)
	fmt.Printf("%s", ui.Muted(source))
	if m.Port != 0 {
		fmt.Printf("%s", ui.Muted(fmt.Sprintf(" · default port %d", m.Port)))
	}
	if m.Homepage != "" {
		fmt.Printf("%s", ui.Muted(" · "+m.Homepage))
	}
	fmt.Println()
	if d := strings.TrimSpace(m.Description); d != "" {
		fmt.Printf("\n%s\n", d)
	}

	if ex := strings.TrimSpace(m.Example); ex != "" {
		fmt.Printf("\n%s\n\n", ui.Header("Example (doze.hcl)"))
		for _, ln := range strings.Split(ex, "\n") {
			fmt.Println("  " + ln)
		}
	}

	if len(m.Config.Arguments) > 0 {
		fmt.Printf("\n%s\n", ui.Header("Arguments"))
		renderArgTable(m.Config.Arguments)
	}
	for _, b := range m.Config.Blocks {
		head := b.Name
		if b.Label != "" {
			head += fmt.Sprintf(" %q", "<"+b.Label+">")
		}
		fmt.Printf("\n%s  %s\n", ui.Header(head+" { … }"), ui.Muted(b.Desc))
		if len(b.Arguments) > 0 {
			renderArgTable(b.Arguments)
		}
	}
	fmt.Println()
}

func renderArgTable(args []metaArg) {
	w := tabwriter.NewWriter(os.Stdout, 0, 2, 3, ' ', 0)
	for _, a := range args {
		name := a.Name
		var marks []string
		if a.Required {
			marks = append(marks, "required")
		}
		if a.Since != "" {
			marks = append(marks, "engine >= "+a.Since)
		}
		if a.Until != "" {
			marks = append(marks, "engine < "+a.Until)
		}
		if len(marks) > 0 {
			name += " " + ui.Muted("("+strings.Join(marks, ", ")+")")
		}
		def := a.Default
		if def == "" {
			def = "-"
		}
		fmt.Fprintf(w, "  %s\t%s\t%s\t%s\n", name, a.Type, def, a.Desc)
	}
	_ = w.Flush()
}
